### ISSUE TITLE
Score Association Statement

### ISSUE THREAD

**Issue by zwhile** [ebreimer/siena-iat-2016#25]
Once again, this isn't game-breaking but just aims to keep consistency.

In the solicitation email, we state that "In this IAT, we are interested in measuring association between Computer Science and gender (Male or Female)."  However, after finishing an IAT, you get the statement that "Your score suggests you associate males with computer science and females with biology" or vice versa.  

Do we want/need to mention the '____ with biology' part if our stated focus is gender association with CS?  It could also be misleading since the IAT essentially shows the Biology association _in comparison_ to CS which most participants will likely have a stronger association/feeling toward.

**Comment by brendon-boldt** [comment]
I see what you are saying. I have the score presented that way since we are specifically using a two-concept IAT instead of single-concept IAT, so I think that the statement is the most accurate representation of what the IAT shows. Now as to what part of the IAT results we are most interested in, that is the single concept of CS, and I do not think that discrepancy is necessarily bad.

You could also ask Tom and Dr. Breimer if you are curious as to what they think.

**Comment by ebreimer** [comment]
I am OK with the discrepancy.  We need to keep the solicitation email simple.  When the score is presented, it is OK to mention "___ with biology" because that might actually be the association that is strong.  I would have preferred to use the single concept IAT, but it is not as well-recognized.

**Comment by zwhile** [comment]
Sounds good, just wanted to make sure that we're all on the same page with that.
